### ISSUE TITLE
bug: ~hsrbs command error

### ISSUE THREAD

**Issue by konnokai** [konnokai/Nadeko-Medusa#2]
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Discord.IUserMessage> Discord.MessageExtensions.ReplyAsync(Discord.IUserMessage, System.String, Boolean, Discord.Embed, Discord.AllowedMentions, Discord.RequestOptions, Discord.MessageComponent, Discord.ISticker[], Discord.Embed[])'.
   at MuteReborn.MuteReborn.HSRStartBetRelic(GuildContext ctx, String text)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at MuteReborn.MuteReborn.HSRStartBetRelic(GuildContext ctx, String text)
--- End of stack trace from previous location ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteAsync(ICommandContext context, IEnumerable`1 argList, IEnumerable`1 paramList, IServiceProvider services)
   ```

**Comment by konnokai** [comment]
重新 build 後正常
